name: Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]

jobs:
  build-apple:
    runs-on: macos-14
    environment: Maven Central
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Rust & cargo
        run: rustup target add aarch64-apple-ios aarch64-apple-darwin x86_64-apple-darwin

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.konan
            sqlx4k-mysql/rust_lib/target
            sqlx4k-postgres/rust_lib/target
            sqlx4k-sqlite/rust_lib/target
          key: rust-lib-cache-apple

      - name: Gradle Build
        run: ./gradlew clean build
#        run: ./scripts/build-apple.sh

#      - name: Gradle Publish
#        run: ./gradlew publish
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
#          MAVEN_SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
#          MAVEN_SIGNING_PASSWORD: ${{ secrets.MAVEN_SIGNING_PASSWORD }}
